version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql-db
      - redis
    networks:
      - backend-network
    environment:
      - 'MARKET_CACHE_TTL=60'
      - 'DB_HOST=mysql-db'
      - 'DB_PORT=3306'
      - 'DB_SCHEMA=fmsdb'
      - 'DB_USER=root'
      - 'DB_PASSWORD=mysqlrootpass'
      - 'MAIL_USERNAME=example@gmail.com'
      - 'MAIL_PASSWORD=mailpass'
      - 'ADMIN_USERNAME=admin@gmail.com'
      - 'ADMIN_PASSWORD=adminpass'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'REDIS_USERNAME=redisuser'
      - 'REDIS_PASSWORD=redispass'
      - 'RESET_PASSWORD_URL=localhost/reset-password?token=%s'
    volumes:
      - ./data:/app/data
  mysql-db:
    image: 'mysql:8.1'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysqlrootpass'
      - 'MYSQL_DATABASE=fmsdb'
      - 'MYSQL_USER=mysqluser'
      - 'MYSQL_PASSWORD=mysqlpass'
  redis:
    image: 'redis:7.2'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: